/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.Correlativo;
import CapaDatos.TipoUsuario;
import CapaNegocio.CorrelativoBD;
import CapaNegocio.TipoUsuarioBD;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROSELITA
 */
public class Correlativo_IU extends javax.swing.JInternalFrame {

    /**
     * Creates new form Correlativo_IU
     */
    public Correlativo_IU() {
        initComponents();
        reportar();
    }

    public void reportar() {
        try {
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

            limpiar_tabla_formulario();

            DefaultTableModel tabla_temporal_correlativo = (DefaultTableModel) this.tabla_reportar_correlativos.getModel();

            CorrelativoBD oCorrelativoBD = new CorrelativoBD();
            String tienda = Login_IU.tienda;
            List<Correlativo> lista_correlativo = oCorrelativoBD.reportarCorrelativo(tienda);

            int cant = lista_correlativo.size();

            for (int i = 0; i < cant; i++) {
                int idcorrelativo = lista_correlativo.get(i).getCoCodigo();
                String serie = lista_correlativo.get(i).getCoSerie();
                String numeracion = lista_correlativo.get(i).getCoNumeracion();
                String documento = lista_correlativo.get(i).getCoDocumento();
                tienda = lista_correlativo.get(i).getTienda();

                Object[] data = {idcorrelativo, serie, numeracion, documento, tienda};
                tabla_temporal_correlativo.addRow(data);

            }
            tabla_reportar_correlativos.setModel(tabla_temporal_correlativo);

            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        } catch (Exception ex) {

            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            ex.printStackTrace();

        }

    }

    private void limpiar() {
        txtCodigo.setText("");
        txtDocumento.setText("");
        txtSerie.setText("");
        txtNumeracion.setText("");

    }

    private void limpiar_tabla_formulario() {

        DefaultTableModel tabla_temporal_correlativos = (DefaultTableModel) tabla_reportar_correlativos.getModel();
        tabla_temporal_correlativos.setRowCount(0);

    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);

    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reportar_correlativos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTienda = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MANTENIMINETO DE CORRELATIVOS");

        tabla_reportar_correlativos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERIE", "NUMERACION", "DOCUMENTO", "TIENDA"
            }
        ));
        tabla_reportar_correlativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reportar_correlativosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reportar_correlativos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("CODIGO");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("SERIE");

        txtSerie.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("NUMERACION");

        txtNumeracion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNumeracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeracionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("DOCUMENTO");

        txtDocumento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("TIENDA");

        cmbTienda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRINCIPAL" }));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/disk.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/report_edit.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/bin_empty.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/cross.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSerie)
                    .addComponent(txtNumeracion)
                    .addComponent(txtDocumento)
                    .addComponent(cmbTienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRegistrar)
                                .addComponent(btnModificar)
                                .addComponent(btnEliminar))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtNumeracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeracionActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        if (txtCodigo.getText().length() > 0) {
            if (txtSerie.getText().length() > 0) {
                if (txtNumeracion.getText().length() > 0) {
                    if (txtDocumento.getText().length() > 0) {

                        Correlativo oCorrelativo = new Correlativo();
                        CorrelativoBD oCorrelativoBD = new CorrelativoBD();

                        oCorrelativo.setCoCodigo(Integer.parseInt(txtCodigo.getText().trim()));
                        oCorrelativo.setCoSerie(txtSerie.getText().trim());
                        oCorrelativo.setCoNumeracion(txtNumeracion.getText().trim());
                        oCorrelativo.setCoDocumento(txtDocumento.getText().toUpperCase().trim());

                        boolean rpta = oCorrelativoBD.modificarCorrelativo(oCorrelativo);
                        if (rpta) {
                            exito("Se modifico con exito");
                            reportar();
                            limpiar();

                        } else {
                            error("Tiene problemas al modificar");
                        }

                    } else {
                        advertencia("Ingrese documento");
                        txtSerie.requestFocus();
                    }
                } else {
                    advertencia("Ingrese la numeracion");
                    txtSerie.requestFocus();
                }

            } else {
                advertencia("Ingrese la serie");
                txtSerie.requestFocus();
            }
        } else {
            advertencia("Falta el codigo para poder modificar");

        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

        if (txtSerie.getText().length() > 0) {
            if (txtNumeracion.getText().length() > 0) {
                if (txtDocumento.getText().length() > 0) {

                    Correlativo oCorrelativo = new Correlativo();
                    CorrelativoBD oCorrelativoBD = new CorrelativoBD();

                    oCorrelativo.setCoSerie(txtSerie.getText().trim());
                    oCorrelativo.setCoNumeracion(txtNumeracion.getText().trim());
                    oCorrelativo.setCoDocumento(txtDocumento.getText().toUpperCase().trim());
                    oCorrelativo.setTienda(cmbTienda.getSelectedItem().toString());

                    boolean rpta = oCorrelativoBD.registrarCorrelativo(oCorrelativo);
                    if (rpta) {
                        exito("Se registro con exito");
                        reportar();
                        limpiar();

                    } else {
                        error("Tiene problemas al registrar");
                    }

                } else {
                    advertencia("Ingrese documento");
                    txtSerie.requestFocus();
                }
            } else {
                advertencia("Ingrese la numeracion");
                txtSerie.requestFocus();
            }

        } else {
            advertencia("Ingrese la serie");
            txtSerie.requestFocus();
        }


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tabla_reportar_correlativosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reportar_correlativosMousePressed
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            int fila_seleccionada = tabla_reportar_correlativos.getSelectedRow();

            txtCodigo.setText(tabla_reportar_correlativos.getValueAt(fila_seleccionada, 0).toString());
            txtSerie.setText(tabla_reportar_correlativos.getValueAt(fila_seleccionada, 1).toString());
            txtNumeracion.setText(tabla_reportar_correlativos.getValueAt(fila_seleccionada, 2).toString());
            txtDocumento.setText(tabla_reportar_correlativos.getValueAt(fila_seleccionada, 3).toString());
            cmbTienda.setSelectedItem(tabla_reportar_correlativos.getValueAt(fila_seleccionada, 4).toString());

        }


    }//GEN-LAST:event_tabla_reportar_correlativosMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        try {

            if (txtCodigo.getText().length() > 0) {
                int aviso = JOptionPane.showConfirmDialog(rootPane, "Estar seguro de eliminar");
                if (aviso == 0) {
                    int codigo = Integer.parseInt(txtCodigo.getText().trim());

                    CorrelativoBD oCorrelativoBD = new CorrelativoBD();

                    boolean rpta = oCorrelativoBD.eliminarCorrelativo(codigo);
                    if (rpta) {
                        exito("Se elimino con exito");
                        reportar();
                        limpiar();

                    } else {
                        error("Tines problemas al eliminar...");
                    }
                }
            } else {
                advertencia("Se necesita el codigo para modificar");

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tabla_reportar_correlativos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNumeracion;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
