/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import CapaNegocio.EntradaProductoBD;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROSELITA
 */
public class Inventario_IU extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inventario_IU
     */
    public Inventario_IU() {
        initComponents();
    }
    
    private void limpiar_tabla_formulario() {
        
        DefaultTableModel tabla_temporal_inventario = (DefaultTableModel) tabla_reporte_inventario.getModel();
        tabla_temporal_inventario.setRowCount(0);
        
    }
    
    private void reportar() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        limpiar_tabla_formulario();
        DefaultTableModel tabla_temporal_inventario = (DefaultTableModel) tabla_reporte_inventario.getModel();
        DefaultTableModel tabla_temporal;
        EntradaProductoBD oEntradaProductoBD = new EntradaProductoBD();
        tabla_temporal = oEntradaProductoBD.inventario();
        int cant_producto = tabla_temporal.getRowCount();
        String medida_final;
        String stock_final;
        double precio_compra_final = 0;
        double dinero_vendiendo_mayor = 0;
        double dinero_vendiendo_unidades = 0;
        double dinero_venta_medida = 0;
        double dinero_invertido = 0;
        
        for (int i = 0; i < cant_producto; i++) {
            
            int idep = Integer.parseInt(tabla_temporal.getValueAt(i, 0).toString());
            String presentacion = tabla_temporal.getValueAt(i, 4).toString();
            String equivalencia = tabla_temporal.getValueAt(i, 5).toString();
            
            if (presentacion.equals(equivalencia)) {
                medida_final = equivalencia;
                precio_compra_final = Double.parseDouble(tabla_temporal.getValueAt(i, 13).toString());
                stock_final = tabla_temporal.getValueAt(i, 11).toString();
                dinero_venta_medida = Double.parseDouble(tabla_temporal.getValueAt(i, 15).toString());
                
            } else {
                medida_final = presentacion;
                precio_compra_final = Double.parseDouble(tabla_temporal.getValueAt(i, 12).toString());
                stock_final = tabla_temporal.getValueAt(i, 10).toString();
                dinero_venta_medida = Double.parseDouble(tabla_temporal.getValueAt(i, 14).toString());
            }
            dinero_vendiendo_mayor += Double.parseDouble(tabla_temporal.getValueAt(i, 14).toString());
            dinero_vendiendo_unidades += Double.parseDouble(tabla_temporal.getValueAt(i, 15).toString());
            
            dinero_invertido = dinero_invertido + precio_compra_final;
            
            String ingreso = tabla_temporal.getValueAt(i, 1).toString();
            String serie = tabla_temporal.getValueAt(i, 2).toString();
            String producto = tabla_temporal.getValueAt(i, 3).toString();
            String marca = tabla_temporal.getValueAt(i, 6).toString();
            String categoria = tabla_temporal.getValueAt(i, 7).toString();
            String lote = tabla_temporal.getValueAt(i, 8).toString();
            String fecha_vcto = tabla_temporal.getValueAt(i, 9).toString();
            String tienda = tabla_temporal.getValueAt(i, 16).toString();
            
            Object[] data = {idep, ingreso, serie, producto, medida_final, marca, categoria, lote, fecha_vcto, stock_final, precio_compra_final, dinero_venta_medida, tienda};
            tabla_temporal_inventario.addRow(data);
            
        }
        
        BigDecimal numero = new BigDecimal(dinero_invertido);
        BigDecimal dineroCompras = numero.setScale(2, RoundingMode.DOWN);
        
        BigDecimal numero1 = new BigDecimal(dinero_vendiendo_mayor);
        BigDecimal dineroGananciaMayor = numero1.setScale(1, RoundingMode.DOWN);
        
        BigDecimal numero2 = new BigDecimal(dinero_vendiendo_unidades);
        BigDecimal dineroGananciaMenor = numero2.setScale(1, RoundingMode.DOWN);
        
        txtCantidad.setText("" + cant_producto);
        txtDineroInvertido.setText("" + dineroCompras);
        txtVendiendoMayor.setText("" + dineroGananciaMayor);
        txtVendiendoMenor.setText("" + dineroGananciaMenor);
        
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_inventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDineroInvertido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVendiendoMenor = new javax.swing.JTextField();
        txtVendiendoMayor = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("INVENTARIO DE PRODUCTOS");

        tabla_reporte_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "INGRESO", "SERIE", "PRODUCTO", "MEDIDA", "MARCA", "CATEGORIA", "LOTE", "FECHAVCTO", "STOCK", "PCOMPRA", "PVENTA", "RIENDA"
            }
        ));
        jScrollPane1.setViewportView(tabla_reporte_inventario);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("DINERO INVERTIDO");

        txtDineroInvertido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtDineroInvertido.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("CANT PRODUCTOS");

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCantidad.setEnabled(false);

        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/impresora1.png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("DINERO VENDIENDO POR MENOR");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("DINERO VENDIENDO POR MAYOR");

        txtVendiendoMenor.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtVendiendoMenor.setEnabled(false);

        txtVendiendoMayor.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtVendiendoMayor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 935, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDineroInvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVendiendoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVendiendoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDineroInvertido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtVendiendoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendiendoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_reporte_inventario;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDineroInvertido;
    private javax.swing.JTextField txtVendiendoMayor;
    private javax.swing.JTextField txtVendiendoMenor;
    // End of variables declaration//GEN-END:variables
}
