/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import java.awt.Dimension;

/**
 *
 * @author ROSELITA
 */
public class Menu_IU extends javax.swing.JFrame {

    /**
     * Creates new form Menu_IU
     */
    public Menu_IU() {
        initComponents();

        this.setExtendedState(this.MAXIMIZED_BOTH);
        menu_mantenimiento.setEnabled(false);
        menu_compras.setEnabled(false);
        menu_item_modificar_precios_productos.setEnabled(false);
        menu_ventas.setEnabled(false);

        btnProductos.setEnabled(false);
        btnCompras.setEnabled(false);
        btnCerrar.setEnabled(false);
        btnVentas.setEnabled(false);
        btnCaja.setEnabled(false);
        menu_caja.setEnabled(false);
        btnIngresos.setEnabled(false);
        btnEgresos.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JSeparator();
        escritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnProductos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnCompras = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnIngresos = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnEgresos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnVentas = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnCaja = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_mantenimiento = new javax.swing.JMenu();
        menu_item_TipoUsuario = new javax.swing.JMenuItem();
        menu_item_usuario = new javax.swing.JMenuItem();
        menu_item_turno = new javax.swing.JMenuItem();
        menu_item_marca = new javax.swing.JMenuItem();
        menu_item_categoria = new javax.swing.JMenuItem();
        menu_item_medida = new javax.swing.JMenuItem();
        menu_item_producto = new javax.swing.JMenuItem();
        menu_item_composicion = new javax.swing.JMenuItem();
        menu_item_proveedor = new javax.swing.JMenuItem();
        menu_item_cuentas_bancarias = new javax.swing.JMenuItem();
        menu_item_correlativo = new javax.swing.JMenuItem();
        menu_compras = new javax.swing.JMenu();
        menu_item_compras = new javax.swing.JMenuItem();
        menu_item_reporte_compra_varios = new javax.swing.JMenuItem();
        menu_item_modificar_precios_productos = new javax.swing.JMenu();
        menu_item_entrada_productos = new javax.swing.JMenuItem();
        menu_item_inventario = new javax.swing.JMenuItem();
        menu_item_modificar_precio_producto = new javax.swing.JMenuItem();
        menu_ventas = new javax.swing.JMenu();
        menu_caja = new javax.swing.JMenu();
        menu_item_egreso = new javax.swing.JMenuItem();
        menu_item_ingreso = new javax.swing.JMenuItem();
        menu_item_cerrar_caja = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(20);

        escritorio.setBackground(new java.awt.Color(0, 0, 0));

        jToolBar1.setBackground(new java.awt.Color(204, 255, 204));
        jToolBar1.setForeground(new java.awt.Color(204, 255, 204));
        jToolBar1.setRollover(true);

        btnProductos.setBackground(new java.awt.Color(204, 255, 204));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/box.png"))); // NOI18N
        btnProductos.setFocusable(false);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProductos);
        jToolBar1.add(jSeparator1);

        btnCompras.setBackground(new java.awt.Color(204, 255, 204));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/compra.png"))); // NOI18N
        btnCompras.setFocusable(false);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCompras);
        jToolBar1.add(jSeparator2);

        btnIngresos.setBackground(new java.awt.Color(204, 255, 204));
        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/ingresos.png"))); // NOI18N
        btnIngresos.setFocusable(false);
        btnIngresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnIngresos);
        jToolBar1.add(jSeparator4);

        btnEgresos.setBackground(new java.awt.Color(204, 255, 204));
        btnEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/egresos.png"))); // NOI18N
        btnEgresos.setFocusable(false);
        btnEgresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEgresos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEgresos);
        jToolBar1.add(jSeparator5);

        btnVentas.setBackground(new java.awt.Color(204, 255, 204));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/venta1.png"))); // NOI18N
        btnVentas.setFocusable(false);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnVentas);
        jToolBar1.add(jSeparator6);

        btnCaja.setBackground(new java.awt.Color(204, 255, 204));
        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/caja_1.png"))); // NOI18N
        btnCaja.setFocusable(false);
        btnCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCaja);
        jToolBar1.add(jSeparator7);

        btnCerrar.setBackground(new java.awt.Color(204, 255, 204));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/cerrar2.png"))); // NOI18N
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCerrar);

        escritorio.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 684, Short.MAX_VALUE))
        );

        menu_mantenimiento.setText("MANTENIMIENTO");
        menu_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mantenimientoActionPerformed(evt);
            }
        });

        menu_item_TipoUsuario.setText("Tipo de Usuarios");
        menu_item_TipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_TipoUsuarioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_TipoUsuario);

        menu_item_usuario.setText("Usuario");
        menu_item_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_usuarioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_usuario);

        menu_item_turno.setText("Turno");
        menu_item_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_turnoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_turno);

        menu_item_marca.setText("Laboratorio");
        menu_item_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_marcaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_marca);

        menu_item_categoria.setText("Categoria");
        menu_item_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_categoriaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_categoria);

        menu_item_medida.setText("Medida");
        menu_item_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_medidaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_medida);

        menu_item_producto.setText("Producto");
        menu_item_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_productoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_producto);

        menu_item_composicion.setText("Composicion");
        menu_item_composicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_composicionActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_composicion);

        menu_item_proveedor.setText("Proveedor");
        menu_item_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_proveedorActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_proveedor);

        menu_item_cuentas_bancarias.setText("Cuentas Bancarias");
        menu_item_cuentas_bancarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cuentas_bancariasActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_cuentas_bancarias);

        menu_item_correlativo.setText("Correlativo");
        menu_item_correlativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_correlativoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_item_correlativo);

        jMenuBar1.add(menu_mantenimiento);

        menu_compras.setText("COMPRAS");

        menu_item_compras.setText("Realizar Compras");
        menu_item_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_comprasActionPerformed(evt);
            }
        });
        menu_compras.add(menu_item_compras);

        menu_item_reporte_compra_varios.setText("Reporte de Compras Varios");
        menu_item_reporte_compra_varios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_reporte_compra_variosActionPerformed(evt);
            }
        });
        menu_compras.add(menu_item_reporte_compra_varios);

        jMenuBar1.add(menu_compras);

        menu_item_modificar_precios_productos.setText("INVENTARIO");
        menu_item_modificar_precios_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_modificar_precios_productosActionPerformed(evt);
            }
        });

        menu_item_entrada_productos.setText("Entrada de Productos");
        menu_item_entrada_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_entrada_productosActionPerformed(evt);
            }
        });
        menu_item_modificar_precios_productos.add(menu_item_entrada_productos);

        menu_item_inventario.setText("Dinero en Inventario");
        menu_item_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_inventarioActionPerformed(evt);
            }
        });
        menu_item_modificar_precios_productos.add(menu_item_inventario);

        menu_item_modificar_precio_producto.setText("Modificar Precio de Productos");
        menu_item_modificar_precio_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_modificar_precio_productoActionPerformed(evt);
            }
        });
        menu_item_modificar_precios_productos.add(menu_item_modificar_precio_producto);

        jMenuBar1.add(menu_item_modificar_precios_productos);

        menu_ventas.setText("VENTAS");
        jMenuBar1.add(menu_ventas);

        menu_caja.setText("CAJA");

        menu_item_egreso.setText("Egreso");
        menu_item_egreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_egresoActionPerformed(evt);
            }
        });
        menu_caja.add(menu_item_egreso);

        menu_item_ingreso.setText("Ingreso");
        menu_item_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_ingresoActionPerformed(evt);
            }
        });
        menu_caja.add(menu_item_ingreso);

        menu_item_cerrar_caja.setText("Ver Caja");
        menu_item_cerrar_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cerrar_cajaActionPerformed(evt);
            }
        });
        menu_caja.add(menu_item_cerrar_caja);

        jMenuBar1.add(menu_caja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void menu_item_TipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_TipoUsuarioActionPerformed
        // TODO add your handling code here:

        TipoUsuario_IU frame = new TipoUsuario_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_TipoUsuarioActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnProductosActionPerformed

    private void menu_item_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_turnoActionPerformed
        // TODO add your handling code here:
        Turno_IU frame = new Turno_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_turnoActionPerformed

    private void menu_item_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_usuarioActionPerformed
        // TODO add your handling code here:
        Usuario_IU frame = new Usuario_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_usuarioActionPerformed

    private void menu_item_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_marcaActionPerformed
        // TODO add your handling code here:
        Marca_IU frame = new Marca_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_marcaActionPerformed

    private void menu_item_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_categoriaActionPerformed
        // TODO add your handling code here:

        Categoria_IU frame = new Categoria_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_categoriaActionPerformed

    private void menu_item_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_medidaActionPerformed
        // TODO add your handling code here:

        Medida_IU frame = new Medida_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_medidaActionPerformed

    private void menu_item_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_productoActionPerformed
        // TODO add your handling code here:
        Producto_IU frame = new Producto_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_productoActionPerformed

    private void menu_item_composicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_composicionActionPerformed
        // TODO add your handling code here:

        Composicion_IU frame = new Composicion_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_composicionActionPerformed

    private void menu_item_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_proveedorActionPerformed
        // TODO add your handling code here:

        Proveedor_IU frame = new Proveedor_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_proveedorActionPerformed

    private void menu_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_mantenimientoActionPerformed

    private void menu_item_cuentas_bancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cuentas_bancariasActionPerformed
        // TODO add your handling code here:

        CuentasBancariasProveedor_IU frame = new CuentasBancariasProveedor_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_cuentas_bancariasActionPerformed

    private void menu_item_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_comprasActionPerformed
        // TODO add your handling code here:

        Compra_IU frame = new Compra_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_comprasActionPerformed

    private void menu_item_reporte_compra_variosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_reporte_compra_variosActionPerformed
        // TODO add your handling code here:
        ReporteComprasVarios_IU frame = new ReporteComprasVarios_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_item_reporte_compra_variosActionPerformed

    private void menu_item_entrada_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_entrada_productosActionPerformed
        // TODO add your handling code here:

        EntradaProductos_IU frame = new EntradaProductos_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_entrada_productosActionPerformed

    private void menu_item_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_inventarioActionPerformed
        // TODO add your handling code here:

        Inventario_IU frame = new Inventario_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_inventarioActionPerformed

    private void menu_item_modificar_precios_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_modificar_precios_productosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_menu_item_modificar_precios_productosActionPerformed

    private void menu_item_modificar_precio_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_modificar_precio_productoActionPerformed
        // TODO add your handling code here:

        ModificarPreciosProductos_IU frame = new ModificarPreciosProductos_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_modificar_precio_productoActionPerformed

    private void menu_item_correlativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_correlativoActionPerformed
        // TODO add your handling code here:

        Correlativo_IU frame = new Correlativo_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_correlativoActionPerformed

    private void menu_item_egresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_egresoActionPerformed
        // TODO add your handling code here:

        Egresos_IU frame = new Egresos_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_egresoActionPerformed

    private void menu_item_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_ingresoActionPerformed
        // TODO add your handling code here:

        Ingresos_IU frame = new Ingresos_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_ingresoActionPerformed

    private void menu_item_cerrar_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cerrar_cajaActionPerformed
        // TODO add your handling code here:

        Caja_IU frame = new Caja_IU();

        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

        frame.show();


    }//GEN-LAST:event_menu_item_cerrar_cajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_IU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCaja;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnCompras;
    public javax.swing.JButton btnEgresos;
    public javax.swing.JButton btnIngresos;
    public javax.swing.JButton btnProductos;
    public javax.swing.JButton btnVentas;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JMenu menu_caja;
    public javax.swing.JMenu menu_compras;
    private javax.swing.JMenuItem menu_item_TipoUsuario;
    private javax.swing.JMenuItem menu_item_categoria;
    private javax.swing.JMenuItem menu_item_cerrar_caja;
    private javax.swing.JMenuItem menu_item_composicion;
    private javax.swing.JMenuItem menu_item_compras;
    private javax.swing.JMenuItem menu_item_correlativo;
    private javax.swing.JMenuItem menu_item_cuentas_bancarias;
    private javax.swing.JMenuItem menu_item_egreso;
    private javax.swing.JMenuItem menu_item_entrada_productos;
    private javax.swing.JMenuItem menu_item_ingreso;
    private javax.swing.JMenuItem menu_item_inventario;
    private javax.swing.JMenuItem menu_item_marca;
    private javax.swing.JMenuItem menu_item_medida;
    private javax.swing.JMenuItem menu_item_modificar_precio_producto;
    public javax.swing.JMenu menu_item_modificar_precios_productos;
    private javax.swing.JMenuItem menu_item_producto;
    private javax.swing.JMenuItem menu_item_proveedor;
    private javax.swing.JMenuItem menu_item_reporte_compra_varios;
    private javax.swing.JMenuItem menu_item_turno;
    private javax.swing.JMenuItem menu_item_usuario;
    public javax.swing.JMenu menu_mantenimiento;
    public javax.swing.JMenu menu_ventas;
    // End of variables declaration//GEN-END:variables
}
