/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.EntradaProducto;
import CapaNegocio.EntradaProductoBD;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROSELITA
 */
public class ModificarPreciosProductos_IU extends javax.swing.JInternalFrame {

    DefaultTableModel tabla_temporal;
    int fila_seleccionada;

    /**
     * Creates new form ModificarPreciosProductos_IU
     */
    public ModificarPreciosProductos_IU() {
        initComponents();
    }

    private void limpiar() {

        txtId.setText("");
        txtSerie.setText("");
        txtProducto.setText("");
        txtLote.setText("");
        txtFechaVcto.setText("");
        txtPresentacion.setText("");
        txtEquivalencia.setText("");
        txtStockPresentacion.setText("");
        txtStockEquivalencia.setText("");
        txtPrecioCompraPresentacion.setText("");
        txtPrecioCompraEquivalencia.setText("");
        txtMargenPresentacion.setText("");
        txtMargenEquivalencia.setText("");
        txtPrecioVentaPresentacion.setText("");
        txtPrecioVentaEquivalencia.setText("");

    }

    private void limpiar_tabla_formulario_producto() {

        DefaultTableModel tabla_reporte_producto_temporal = (DefaultTableModel) tabla_reporte_producto.getModel();
        tabla_reporte_producto_temporal.setRowCount(0);

    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);

    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_producto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        txtFechaVcto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEquivalencia = new javax.swing.JTextField();
        txtStockPresentacion = new javax.swing.JTextField();
        txtStockEquivalencia = new javax.swing.JTextField();
        txtPrecioCompraPresentacion = new javax.swing.JTextField();
        txtPrecioCompraEquivalencia = new javax.swing.JTextField();
        txtMargenPresentacion = new javax.swing.JTextField();
        txtMargenEquivalencia = new javax.swing.JTextField();
        txtPrecioVentaPresentacion = new javax.swing.JTextField();
        txtPrecioVentaEquivalencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MODIFICAR PRECIO DE PRODUCTOS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("PRODUCTO");

        txtBuscarProducto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtBuscarProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarProductoFocusLost(evt);
            }
        });
        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyPressed(evt);
            }
        });

        tabla_reporte_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERIE", "PRODUCTO", "LOTE", "FECHAVCTO", "TIENDA"
            }
        ));
        tabla_reporte_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_productoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_producto);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTO A MODIFICAR PRECIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        jPanel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("ID");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtId.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("SERIE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("PRODUCTO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("LOTE");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("FRCHAVCTO");

        txtSerie.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtSerie.setEnabled(false);

        txtProducto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtProducto.setEnabled(false);

        txtLote.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtLote.setEnabled(false);

        txtFechaVcto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtFechaVcto.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("MEDIDA");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("PRESENTACION");

        txtPresentacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtPresentacion.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setText("EQUIVALENCIA");

        txtEquivalencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtEquivalencia.setEnabled(false);

        txtStockPresentacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtStockPresentacion.setEnabled(false);

        txtStockEquivalencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtStockEquivalencia.setEnabled(false);

        txtPrecioCompraPresentacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtPrecioCompraPresentacion.setEnabled(false);

        txtPrecioCompraEquivalencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtPrecioCompraEquivalencia.setEnabled(false);

        txtMargenPresentacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtMargenPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMargenPresentacionKeyReleased(evt);
            }
        });

        txtMargenEquivalencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtMargenEquivalencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMargenEquivalenciaActionPerformed(evt);
            }
        });
        txtMargenEquivalencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMargenEquivalenciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMargenEquivalenciaKeyReleased(evt);
            }
        });

        txtPrecioVentaPresentacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtPrecioVentaPresentacion.setEnabled(false);

        txtPrecioVentaEquivalencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtPrecioVentaEquivalencia.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setText("STOCK");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setText("PRECIO COMPRA");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setText("MARGEN");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("PRECIO VENTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaVcto, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(txtPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtEquivalencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStockPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStockEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioCompraPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioCompraEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMargenPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(txtMargenEquivalencia))
                            .addComponent(jLabel12))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPrecioVentaPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(txtPrecioVentaEquivalencia)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVcto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioCompraPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMargenPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioVentaPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioCompraEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMargenEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioVentaEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/lapiz.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaPresentacion/Images/cerrar.png"))); // NOI18N
        btnCerrar.setText("CERRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarProducto))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMargenEquivalenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMargenEquivalenciaActionPerformed

    private void txtBuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyPressed
        // TODO add your handling code here:

        limpiar_tabla_formulario_producto();

        String producto = txtBuscarProducto.getText();

        if (txtBuscarProducto.getText().length() > 2) {

            DefaultTableModel tabla_reporte_producto_temporal = (DefaultTableModel) tabla_reporte_producto.getModel();
            EntradaProductoBD oEntradaProductoBD = new EntradaProductoBD();

            tabla_temporal = oEntradaProductoBD.buscarProductoXdescripcion(producto);

            int cant = tabla_temporal.getRowCount();

            for (int i = 0; i < cant; i++) {

                String id = tabla_temporal.getValueAt(i, 0).toString();
                String serie = tabla_temporal.getValueAt(i, 3).toString();
                String descripcion = tabla_temporal.getValueAt(i, 4).toString();
                String lote = tabla_temporal.getValueAt(i, 2).toString();
                String fecha_vcto = tabla_temporal.getValueAt(i, 11).toString();
                String tienda = tabla_temporal.getValueAt(i, 23).toString();

                Object[] data = {id, serie, descripcion, lote, fecha_vcto, tienda};
                tabla_reporte_producto_temporal.addRow(data);

            }

        }


    }//GEN-LAST:event_txtBuscarProductoKeyPressed

    private void tabla_reporte_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_productoMousePressed
        // TODO add your handling code here:

        fila_seleccionada = tabla_reporte_producto.getSelectedRow();

        txtId.setText("" + tabla_reporte_producto.getValueAt(fila_seleccionada, 0));
        txtLote.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 2));
        txtSerie.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 3));
        txtProducto.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 4));
        txtFechaVcto.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 11));
        txtPresentacion.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 9));
        txtEquivalencia.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 10));
        txtStockPresentacion.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 12));
        txtStockEquivalencia.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 13));
        txtPrecioCompraPresentacion.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 14));
        txtPrecioCompraEquivalencia.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 15));

        txtPrecioVentaPresentacion.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 18));
        txtPrecioVentaEquivalencia.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 20));

        String presentacion = txtPresentacion.getText();
        String equivalencia = txtEquivalencia.getText();

        if (presentacion.equals(equivalencia)) {
            txtMargenPresentacion.setEnabled(false);
            txtMargenPresentacion.setText("0");
            txtMargenEquivalencia.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 17));

        } else {
            txtMargenPresentacion.setEnabled(true);
            txtMargenPresentacion.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 16));
            txtMargenEquivalencia.setText("" + tabla_temporal.getValueAt(fila_seleccionada, 17));

        }


    }//GEN-LAST:event_tabla_reporte_productoMousePressed

    private void txtMargenPresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenPresentacionKeyReleased
        // TODO add your handling code here:
        try {
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
            DecimalFormat df = new DecimalFormat("#.#", symbols);

            double precio_compra_presentacion = Double.parseDouble(txtPrecioCompraPresentacion.getText().trim());

            double margen = Integer.parseInt(txtMargenPresentacion.getText().trim());

            double ganancia_presentacion = precio_compra_presentacion * (margen / 100);

            double precio_venta_presentacion = precio_compra_presentacion + ganancia_presentacion;

            double redondeado_presentacion = Math.round(precio_venta_presentacion);

            txtPrecioVentaPresentacion.setText("" + df.format(redondeado_presentacion));

        } catch (Exception e) {
        }


    }//GEN-LAST:event_txtMargenPresentacionKeyReleased

    private void txtMargenEquivalenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMargenEquivalenciaKeyPressed

    private void txtMargenEquivalenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaKeyReleased
        // TODO add your handling code here:

        try {
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
            DecimalFormat df = new DecimalFormat("#.#", symbols);

            double precio_compra_equivalencia = Double.parseDouble(txtPrecioCompraEquivalencia.getText().trim());

            double margen = Integer.parseInt(txtMargenEquivalencia.getText().trim());

            double ganancia_equivalencia = precio_compra_equivalencia * (margen / 100);

            double precio_venta_equivalencia = precio_compra_equivalencia + ganancia_equivalencia;

            String redondeado_equivalencia = df.format(precio_venta_equivalencia);

            txtPrecioVentaEquivalencia.setText(redondeado_equivalencia);

        } catch (Exception e) {
        }

    }//GEN-LAST:event_txtMargenEquivalenciaKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        try {
            int aviso = JOptionPane.showConfirmDialog(rootPane, "Estas a punto de modificar los precios de ventas de " + txtProducto.getText());

            if (aviso == 0) {

                int margenPresentacion = Integer.parseInt(txtMargenPresentacion.getText());
                int margenEquivalencia = Integer.parseInt(txtMargenEquivalencia.getText());
                double precioVentapresentacio = Double.parseDouble(txtPrecioVentaPresentacion.getText());
                double precioVentaEquivalencia = Double.parseDouble(txtPrecioVentaEquivalencia.getText());
                int identrada_producto = Integer.parseInt(txtId.getText());
                if (txtMargenPresentacion.getText().length() > 0) {
                    if (txtMargenEquivalencia.getText().length() > 0) {
                        EntradaProducto oEntradaProducto = new EntradaProducto();
                        EntradaProductoBD oEntradaProductoBD = new EntradaProductoBD();

                        oEntradaProducto.setMargenGananciaPresentacion(margenPresentacion);
                        oEntradaProducto.setMargenGananciaEquivalencia(margenEquivalencia);
                        oEntradaProducto.setPrecioVentaPresentacionMayor(precioVentapresentacio);
                        oEntradaProducto.setPrecioVentaEquivalenciaMayor(precioVentaEquivalencia);
                        oEntradaProducto.setIdep(identrada_producto);

                        boolean rpta = oEntradaProductoBD.modificarPrecioProducto(oEntradaProducto);

                        if (rpta) {
                            exito("Se modifico los precios de ventas corre ctamente...");
                            limpiar();

                        } else {
                            error("Tienes problemas al modificar precios");
                        }

                    } else {
                        advertencia("No debe estar vacio");
                        txtMargenPresentacion.requestFocus();
                    }

                } else {
                    advertencia("No debe estar vacio");
                    txtMargenPresentacion.requestFocus();

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBuscarProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductoFocusGained
        // TODO add your handling code here:
        txtBuscarProducto.setBackground(Color.yellow);
    }//GEN-LAST:event_txtBuscarProductoFocusGained

    private void txtBuscarProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductoFocusLost
        // TODO add your handling code here:

        txtBuscarProducto.setBackground(Color.white);

    }//GEN-LAST:event_txtBuscarProductoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable tabla_reporte_producto;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtEquivalencia;
    private javax.swing.JTextField txtFechaVcto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMargenEquivalencia;
    private javax.swing.JTextField txtMargenPresentacion;
    private javax.swing.JTextField txtPrecioCompraEquivalencia;
    private javax.swing.JTextField txtPrecioCompraPresentacion;
    private javax.swing.JTextField txtPrecioVentaEquivalencia;
    private javax.swing.JTextField txtPrecioVentaPresentacion;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtStockEquivalencia;
    private javax.swing.JTextField txtStockPresentacion;
    // End of variables declaration//GEN-END:variables
}
